server:
  port: 8080

spring:
  application:
    name: max-order
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Post123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: t_order
  jpa:
    properties:
      hibernate:
        default_schema: t_order
  redis:
    host: max-redis
    port: 6379

management:
  endpoints:
    web:
      base-path: /orders/actuator
      exposure:
        include: ['*', 'prometheus']

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka/

springdoc:
  api-docs:
    path: /orders/v3/api-docs
  swagger-ui:
    path: /orders/swagger-ui